### ISSUE TITLE
Newtonsoft.Json dependency trouble

### ISSUE THREAD

**Issue by pavelhritonenko** [mbraceproject/FsPickler#56] opened 2015-07-30 13:47 UTC
I have an issue when I want to stick Newtonsoft.Json to ~6.0 version

> An unhandled exception of type 'System.IO.FileLoadException' occurred in FsPickler.dll
> 
> Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

https://github.com/pavelhritonenko/fspickler-newtonsoft - repository for reproduce issue

**Comment by eiriktsarpalis** [comment] 2015-07-30 22:12
You need to specify a [binding redirect](https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx) for Newtonsoft.Json if you are using a version different than 7.0.

**Comment by pavelhritonenko** [comment] 2015-07-31 07:57
@eiriktsarpalis I have [one](https://github.com/pavelhritonenko/fspickler-newtonsoft/blob/master/fspickler-newtonsoft/App.config#L11-L14) default generated by Packet, but it strange for me that FsPickler compiled with version higher than minimal supported. What do you think, should I address this issue to Paket developers?

**Comment by eiriktsarpalis** [comment] 2015-07-31 07:59
Yes I've seen this. Not sure if bug or by design.

**Comment by mvkra** [comment] 2015-11-12 22:31
Bit late to the party - just trying this framework now and with Newtonsoft.Json 7 out this is causing me headaches since another library I'm pulling needs a different version than this one. Is it possible to just remove the dependency of Newtonsoft.Json from the codebase? Maybe a stupid question. Newtonsoft is MIT licensed; doesn't that mean worse comes to worse you can just use the JsonWriter and BsonWriter's as code inside the library? I know RavenDB has done this for their JSON serialisation. Not sure if you are relying on any functionality to help with F# types for example; it would simplify things a lot.

**Comment by eiriktsarpalis** [comment] 2015-11-12 22:40
@mvkra I once tried doing that, but the JsonWriter/Reader types depend on a significant segment of the Json.Net library. I would like to write my own JsonWriter/Reader implementations using F# at some point, I'm sure it would benefit deserialization performance. Haven't found the time to do this yet.

Does adding a binding redirect not fix your problem?

**Comment by mvkra** [comment] 2015-11-13 04:09
It does if I play with it right but I would rather just use Json.net then
most of the time (would rather just use one library rather than two). Keeps
it simple. Of course that means I don't use this library hence the
suggestion.

**Comment by dsyme** [comment] 2017-06-07 22:07
Closing this old discussion/question

**Closed by dsyme** 2017-06-07 22:07 UTC
